# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  HQChan
subtitle: stay hungry，stay foolish
name: HQChan
email: 13902021104@139.com
description: 本博客是HQChan分享，记录工作中遇到的相关经历和技术的站点，主要涉及redis，Netty，spring，springboot，python大数据分析及爬虫
keywords: redis，Netty，spring，springboot，python大数据分析及爬虫，
encoding: "utf-8"
favicon: favicon.png 

repository: haiqiangchen/haiqiangchen.github.io
github_url: https://github.com/haiqiangchen
#url: http://www.haiqiangchen.com
#enforce_ssl: ityouknow.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:

  -
    href: /
    label: Home

  -
    href: /redis.html
    label: redis

  -
    href: /netty.html
    label: netty

  -
    href: /archives.html
    label: Archives

  -
    href: /link.html
    label: Link

  -
    href: /about.html
    label: About


# labels. my blog key words
labels:

    href: /open-source.html
    name: Code   

# selected articles
classes:

  -
    href: /redis.html
    name: redis
    describe: redis的集群，安装和应用场景

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 
    repo: blog-comments
    oauth:
        client_id: 
        client_secret: 
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: 
    repo: blog-comments
    clientID: 
    clientSecret: 
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
